export const floatingTopicsList = [
  "Snot",
  "Gravity",
  "T-Rex",
  "Spies",
  "Drool",
  "Blobfish",
  "Venus fly trap",
  "Quicksand",
  "Slime",
  "Maggots",
  "Haunted houses",
  "Cow dung",
  "Farts",
  "Invisible ink",
  "Fossils",
  "Tornadoes",
  "Pottery",
  "Stink bombs",
  "Secret codes",
  "Camouflage",
  "Tie-dye",
  "Dreamcatchers",
  "Origami",
  "Glow-in-the-dark",
  "Lasers",
  "Meteors",
  "Lightning",
  "Volcanoes",
  "Puppets",
  "Rockets",
  "Treasure maps",
  "Friendship bracelets",
  "Rocks",
  "Cool inventions",
  "Unusual animals",
  "Weird ice-cream flavours",
  "Aliens",
  "Ghosts",
  "Fireworks",
  "Potions",
  "Eyeballs",
  "Titanic",
  "Hieroglyphics",
  "Medieval weapons",
  "Pyramids",
  "Rubik's Cube",
  "Fingernails",
  "Rubber ducks",
  "Komodo dragons",
  "Snakes",
  "Poisonous animals",
  "Killer whales",
  "Lions",
  "Goblin shark",
  "Bull shark",
  "Scorpions",
  "Praying mantis",
  "Bigfoot",
  "Vampires",
  "Chupacabra",
  "Loch Ness Monster",
  "Poisonous plants",
  "Carnivorous plants",
  "Salamanders",
  "Platypus",
  "Narwhal",
  "Snow leopard",
  "Spider crab",
  "Okapi",
  "Sloth",
  "Blue-footed booby",
  "Electric eel",
  "Fennec fox",
  "Red panda",
  "Tiger shark",
  "Sea urchin",
  "Jellyfish",
  "Hammerhead shark",
  "Great white shark",
  "Giant squid",
  "Dumbo octopus",
  "Seahorse",
  "Tiger  ",
  "Gorilla",
  "Giant anteater",
  "Blue-ringed octopus",
  "Honey badger",
  "Mosquitos",
  "Mummies",
  "Tombs",
  "Animal Camouflage",
  "Nocturnal animals",
  "Animal defense",
  "Echolocation",
  "Sea anemone",
  "X-ray",
  "Fingerprints",
  "Belly button",
  "Animal superpowers",
  "Boreal forest",
  "Temperate forest",
  "Tropical forest",
  "Leafy seadragon",
  "Angler fish",
  "Sea sponges",
  "Scarab beetle",
  "Brazilian treehopper",
  "Glass frog",
  "Peanut-head bug",
  "Lungfish",
  "Manatee",
  "Anaconda",
  "Python",
  "Nile Crocodile",
  "Bermuda Triangle",
  "Rainbows",
  "Atoms",
  "Moons",
  "Fault Lines",
  "Techtonic plates",
  "Eruptions",
  "Hot springs",
  "Magnets",
  "Stalacites",
  "Stalagmites",
  "Cyclones",
  "Hurricanes",
  "Sinkholes",
  "Landslides",
  "Earthquakes",
  "Tsunamis",
  "Constellations",
  "Satalites",
  "Black holes",
  "Supernovas",
  "Comets",
  "Galaxies",
  "Space stations",
  "Exoplanets",
  "Stars",
  "Igloos",
  "Ninjas",
  "Crystals",
  "Gravity",
  "Balloons",
  "Bacteria",
  "Fungus",
  "Parasites",
  "Germs",
  "Sunshine",
  "Photosynthesis",
  "Symbiosis",
  "Giant trees",
  "Corpse flower",
  "Tiny trees",
  "Ghost orchid",
  "Living dinosaurs",
  "DNA",
  "Genes",
  "Bees",
  "Fastest animals",
  "Slowest animals",
  "Nerves",
  "Muscles",
  "Skeletons",
  "Tongues",
  "Strangest creepy-crawlies",
  "Taste buds",
  "Weird smells",
  "Treasure hunts",
  "Lost treasure",
  "Castles",
  "Metal detectors",
  "Vikings",
  "Romans",
  "Ancient Greeks",
  "Aztecs",
  "Ancient gladiators",
  "Incas",
  "Mayans",
  "Middle Ages",
  "Outlaws",
  "Meteorites",
  "Asteroids",
  "Dwarf planets",
  "Stegosaurus",
  "Triceratops",
  "Diplodocus",
  "Velociraptors",
  "Frogspawn",
  "Dragonflies",
  "Shells",
  "Shark teeth",
  "Snowflakes",
  "Petrified wood",
  "Wasp nests",
  "Dung beetle",
  "Spider webs",
  "Owl pellets",
  "Poop",
  "Seasons",
  "Worms",
  "Shipwrecks",
  "Acid",
  "Compass",
  "Hot air balloon",
  "Diggers",
  "Tractors",
  "Trains",
  "Snail trail",
  "Nature's nose pickers",
  "Sneezing",
  "Zombie ant fungus",
  "Tarantulas",
  "Rainbow plant",
  "Star-nosed mole",
  "Blind cave fish",
  "See-through animals",
  "Jumping beans",
  "Dancing spiders",
  "Boxing crabs",
  "Pufferfish",
  "Flying snakes",
  "Flying fox",
  "Piranha",
  "Firefly",
  "King cobra",
  "Rattlesnakes",
  "Galapagos giant tortoise",
  "Submarines",
  "Helicopters",
  "Dynamite",
  "Microscopes",
  "Brains",
  "Heart",
  "Scabs",
  "Blood",
  "Tapeworm",
  "Guts",
  "Earwax",
  "Telescopes",
  "Wigs",
  "Claws",
  "Toenails",
  "Electricity",
  "WWI",
  "WWII",
  "Ice Age",
  "Bronze Age",
  "Stone Age",
  "Anglo-Saxons",
  "Ancient Egyptians",
  "Arctic",
  "Antarctic",
  "Icebergs",
  "Pluto",
  "Venus",
  "Jupiter",
  "Uranus",
  "Earth",
  "Sun",
  "Mercury",
  "Mars",
  "Neptune",
  "Saturn",
  "Mountains",
  "The Black Death",
  "Knights",
  "Queens",
  "Kings",
  "Endangered species",
  "Energy",
  "Dark matter",
  "Alligators",
];
