export const floatingTopicsList = [
  "snot",
  "gravity",
  "t-rex",
  "spies",
  "drool",
  "blob fish",
  "venus fly trap",
  "quicksand",
  "slime",
  "maggots",
  "haunted houses",
  "cow dung",
  "farts",
  "invisible ink",
  "fossils",
  "tornadoes",
  "pottery",
  "stink bombs",
  "secret codes",
  "camouflage",
  "tie-dye",
  "dreamcatchers",
  "origami",
  "glow in the dark",
  "lasers",
  "meteors",
  "lightning",
  "volcanoes",
  "puppets",
  "rockets",
  "treasure maps",
  "friendship bracelets",
  "rocks",
  "cool inventions",
  "unusual animals",
  "weird ice cream flavours",
  "aliens",
  "ghosts",
  "fireworks",
  "potions",
];
