export const floatingTopicsList = [
  "Snot",
  "Gravity",
  "T-Rex",
  "Spies",
  "Drool",
  "Blobfish",
  "Venus Fly Trap",
  "Quicksand",
  "Slime",
  "Maggots",
  "Haunted houses",
  "Cow dung",
  "Farts",
  "Invisible ink",
  "Fossils",
  "Tornadoes",
  "Pottery",
  "Stink bombs",
  "Secret codes",
  "Camouflage",
  "Tie-dye",
  "Dreamcatchers",
  "Origami",
  "Glow-in-the-dark",
  "Lasers",
  "Meteors",
  "Lightning",
  "Volcanoes",
  "Puppets",
  "Rockets",
  "Treasure maps",
  "Friendship bracelets",
  "Rocks",
  "Cool inventions",
  "Unusual animals",
  "Weird ice-cream flavours",
  "Aliens",
  "Ghosts",
  "Fireworks",
  "Potions",
  "Eyeballs",
  "World's tallest plants",
  "World's shortest plants",
  "World's tallest animals",
  "World's shortest animals",
  "Longest Time Spent Balancing on One Foot",
  "Lions",
  "Killer whales",
  "Poisonous animals",
  "Snakes",
  "Komodo dragons",
  "Largest collection of rubber ducks",
  "Longest fingernails",
  "Fastest time to solve a Rubik's Cube",
  "Longest time spent gaming",
  "Largest gathering of people dressed as penguins",
  "Most hot dogs eaten in 10 minutes",
  "Longest time spent hula hooping",
];
