export const preGenRiddles = [
  {
    contentType: "riddle",
    body: "What has a bottom at the top?",
    hint: "You have two of them...",
    answer: "Your legs. 🦵🦵",
  },
  {
    contentType: "riddle",
    body: "What gets wetter the more it dries?",
    hint: "You use it after a bath...",
    answer: "A towel 🛀",
  },
  {
    contentType: "riddle",
    body: "What has hands but can not clap?",
    hint: "It's always ticking...",
    answer: "A clock 🕰️",
  },
  {
    contentType: "riddle",
    body: "What is made of water but if you put it into water it will die?",
    hint: "You can make in the freezer...",
    answer: "An ice cube ❄️",
  },
  {
    contentType: "riddle",
    body: "What has keys but can’t open locks?",
    hint: "You can make music with it...",
    answer: "A piano 🎹",
  },
  {
    contentType: "riddle",
    body: "What can fly without wings?",
    hint: "You might find it on a windy day...",
    answer: "A kite 🪁",
  },
  {
    contentType: "riddle",
    body: "What becomes smaller when you turn it upside down?",
    hint: "It's a number...",
    answer: "The number 9",
  },
  {
    contentType: "riddle",
    body: "What lights up a football stadium at night?",
    hint: "Every room has one...",
    answer: "A football match 🔦",
  },
  {
    contentType: "riddle",
    body: "What has a neck but no head?",
    hint: "It holds your drinks...",
    answer: "A bottle. 🍼",
  },
  {
    contentType: "riddle",
    body: "What is full of holes but still holds water?",
    hint: "It lives in the kitchen...",
    answer: "A sponge! 🧽",
  },
  {
    contentType: "riddle",
    body: "What runs all around a garden, yet never moves?",
    hint: "You can't jump over it...",
    answer: "A fence. 🚧",
  },
  {
    contentType: "riddle",
    body: "What begins with T, ends with T and has T in it?",
    hint: "You pour tea into it!",
    answer: "A teapot. ☕",
  },

  {
    contentType: "riddle",
    body: "What can you hold in your right hand, but not in your left?",
    hint: "Think about your hands.",
    answer: "Your left hand... 🤲",
  },

  {
    contentType: "riddle",
    body: "What has to be broken before you can use it?",
    hint: "It's breakfast time!",
    answer: "An egg 🥚",
  },
  {
    contentType: "riddle",
    body: "What type of cheese is made backward?",
    hint: "It's a common cheese!",
    answer: "Edam",
  },
  {
    contentType: "riddle",
    body: "What has 88 keys but can’t open a door?",
    hint: "It can play music...",
    answer: "A piano 🎹",
  },

  {
    contentType: "riddle",
    body: "What kind of tree can you carry in your hand?",
    hint: "It's a snack...",
    answer: "A palm tree (palm of your hand)! 🌴",
  },
  {
    contentType: "riddle",
    body: "I am not alive, but I grow; I don't have lungs, but I need air; I don't have a mouth, but water kills me. What am I?",
    hint: "You use it to light a fire...",
    answer: "A flame. 🔥",
  },
  {
    contentType: "riddle",
    body: "The more you take, the more you leave behind. What am I?",
    hint: "You leave these on a beach...",
    answer: "Footprints. 👣",
  },

  {
    contentType: "riddle",
    body: "In a one-story pink house, there was a pink person, a pink cat, a pink fish, a pink computer, a pink chair, a pink table, a pink telephone, a pink shower– everything was pink! What colour were the stairs?",
    hint: "Think about the house...",
    answer: "There weren’t any stairs, it was a one story house!",
  },
  {
    contentType: "riddle",
    body: "I shave every day, but my beard stays the same. What am I?",
    hint: "Not a person...",
    answer: "A barber. ✂️",
  },
  {
    contentType: "riddle",
    body: "What has lots of eyes, but can’t see?",
    hint: "It's a type of food...",
    answer: "A potato 🥔",
  },
  {
    contentType: "riddle",
    body: "What can travel all around the world without leaving its corner?",
    hint: "It sticks to an envelope...",
    answer: "A stamp 📮",
  },
  {
    contentType: "riddle",
    body: "What kind of band never plays music?",
    hint: "You can stretch it...",
    answer: "A rubber band! 🩴",
  },
  {
    contentType: "riddle",
    body: "Which letter of the alphabet has the most water?",
    hint: "Think about the sound of the letters...",
    answer: "The letter C (sea) 🌊",
  },

  {
    contentType: "riddle",
    body: "What is so delicate that saying its name breaks it?",
    hint: "It requires silence...",
    answer: "Silence 🤫",
  },
  {
    contentType: "riddle",
    body: "What has a face and two hands but no arms or legs?",
    hint: "It tells time...",
    answer: "A clock 🕗",
  },
  {
    contentType: "riddle",
    body: "What kind of room has no doors or windows?",
    hint: "It's also a plant...",
    answer: "A mushroom 🍄",
  },
  {
    contentType: "riddle",
    body: "What has many needles, but isn’t used for sewing?",
    hint: "It's often decorated during Christmas...",
    answer: "A Christmas tree 🎄",
  },
  {
    contentType: "riddle",
    body: "What is always coming, but never arrives?",
    hint: "You cannot stop it...",
    answer: "Tomorrow ⌛️",
  },
  {
    contentType: "riddle",
    body: "What can be cracked, made, told, and played?",
    hint: "It's fun to share with friends...",
    answer: "A joke 😄",
  },
  {
    contentType: "riddle",
    body: "What can fill a room but takes up no space?",
    hint: "You can't see or touch it...",
    answer: "Light 💡",
  },
  {
    contentType: "riddle",
    body: "What goes up and doesn’t come back down?",
    hint: "As time goes by, it increases...",
    answer: "Your age 🎂",
  },
  {
    contentType: "riddle",
    body: "What breaks yet never falls, and what falls yet never breaks?",
    hint: "Think about day and night...",
    answer: "Day breaks and night falls 🌞 🌚",
  },
  {
    contentType: "riddle",
    body: "What runs, but never walks; murmurs, but never talks; has a bed, but never sleeps; and has a mouth, but never eats?",
    hint: "It flows...",
    answer: "A river 🌊",
  },
  {
    contentType: "riddle",
    body: "I start out tall, but the longer I stand, the shorter I grow. What am I?",
    hint: "You use me when it's dark...",
    answer: "A candle 🕯️",
  },
  {
    contentType: "riddle",
    body: "What begins with an ‘E’ and only contains one letter?",
    hint: "You get it in the post...",
    answer: "An envelope 💌",
  },
  {
    contentType: "riddle",
    body: "What has keys but can't open any kind of lock?",
    hint: "You use it to type...",
    answer: "A keyboard 💻",
  },
  {
    contentType: "riddle",
    body: "What can you catch but never throw?",
    hint: "You get it when someone is sick...",
    answer: "A cold 🤧",
  },
  {
    contentType: "riddle",
    body: "Where does one wall meet the other wall?",
    hint: "Think about the parts of a room...",
    answer: "On the corner. 🏠",
  },
  {
    contentType: "riddle",
    body: "What do you call a witch who lives at the beach?",
    hint: "Think about food...",
    answer: "A sand-witch! 🏖️",
  },
  {
    contentType: "riddle",
    body: "What goes up and down, but never moves?",
    hint: "You use this to go to different floors...",
    answer: "Stairs",
  },
  {
    contentType: "riddle",
    body: "What has teeth but can’t bite?",
    hint: "You might use it to get dressed...",
    answer: "A comb 🪒",
  },
  {
    contentType: "riddle",
    body: "What has a thumb and four fingers, but is not a hand?",
    hint: "It's made of fabric...",
    answer: "A glove 🧤",
  },
];
